### ISSUE TITLE
I'm getting two errors when attempting to run the emote parser and I don't know why.

### ISSUE THREAD

**Issue by chrisyroid** [smilefx/tmi-emote-parse#4]
The first one is when it starts up, the FFZ emotes fail to load.

`Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  channel: 'twitchdev',
  error: 'Failed to load FFZ channel emotes for twitchdev'
})
    at new NodeError (node:internal/errors:371:5)
    at ParseEmitter.emit (node:events:379:17)
    at /home/tdcxmx/nodevenv/twitch_chat/16/lib/node_modules/tmi-emote-parse/index.js:85:36
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    channel: 'twitchdev',
    error: 'Failed to load FFZ channel emotes for twitchdev'
  }
}`

Also, if I try to send a test message, I get this:

`Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ channel: 'test', error: 'The channel test has not been loaded yet' })
    at new NodeError (node:internal/errors:371:5)
    at ParseEmitter.emit (node:events:379:17)
    at replaceBTTV (/home/tdcxmx/nodevenv/twitch_chat/16/lib/node_modules/tmi-emote-parse/index.js:614:24)
    at replaceMessage (/home/tdcxmx/nodevenv/twitch_chat/16/lib/node_modules/tmi-emote-parse/index.js:471:15)
    at Object.exports.replaceEmotes (/home/tdcxmx/nodevenv/twitch_chat/16/lib/node_modules/tmi-emote-parse/index.js:768:12)
    at client.<anonymous> (/home/tdcxmx/twitch_chat/server.js:25:29)
    at client.EventEmitter.emit (/home/tdcxmx/nodevenv/twitch_chat/16/lib/node_modules/tmi.js/lib/events.js:88:13)
    at client.emits (/home/tdcxmx/nodevenv/twitch_chat/16/lib/node_modules/tmi.js/lib/client.js:90:13)
    at client.handleMessage (/home/tdcxmx/nodevenv/twitch_chat/16/lib/node_modules/tmi.js/lib/client.js:1117:13)
    at /home/tdcxmx/nodevenv/twitch_chat/16/lib/node_modules/tmi.js/lib/client.js:1228:9 {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    channel: 'test',
    error: 'The channel test has not been loaded yet'
  }
}`

In the second one, it looks like it's listening to the channel but thinks the channel is somehow the test message.

**Comment by chrisyroid** [comment]
Nevermind, I solved it. Apparently I had to turn off the services I wasn't using. Also, in the example, `channel, userstate, message, self` is wrong. It's actually `message, userstate, channel, self`
